Repository rethinkdb/rethinkdb-python, pull requests merged in 2018-08, with the labels that each got.

#13 Codacy errors pass 1
  rebirthdb/ast.py
  rebirthdb/asyncio_net/net_asyncio.py
  rebirthdb/errors.py
  rebirthdb/gevent_net/net_gevent.py
  rebirthdb/handshake.py
  rebirthdb/tornado_net/net_tornado.py
  rebirthdb/twisted_net/net_twisted.py
  rebirthdb/utils_common.py
Labels: quality issue fix

#14 Add issue template for bug reports.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: quality issue fix

#15 Add coverage badge
  README.md
Labels: documentation

#20 Extending readme and makefile with the remote integration testing
  .travis.yml
  Makefile
  README.md
Labels: documentation

#21 Fix env variable table display
  README.md
Labels: documentation

#32 Add tests for cursor/next
  tests/integration/test_next.py
  tests/integration/test_repl.py
Labels: quality issue fix

#35 Add integration tests for closing the cursor
  rebirthdb/net.py
  tests/integration/test_close.py
Labels: quality issue fix

#34 Integration test for loops
  tests/integration/test_for.py
Labels: quality issue fix

#33 Create connection integration.
  rebirthdb/net.py
  tests/helpers.py
  tests/integration/test_ping.py
Labels: quality issue fix

#38 Add database tests
  tests/integration/test_database.py
Labels: quality issue fix

#37 Extend logger to be able to write to stdout/stderr
  rebirthdb/logger.py
  tests/test_logger.py
Labels: enhancement

#36 Extend and refactor cursor tests
  tests/integration/test_close.py
  tests/integration/test_cursor.py
  tests/integration/test_database.py
  tests/integration/test_for.py
Labels: quality issue fix

#39 Add table integration tests
  tests/integration/test_table.py
Labels: quality issue fix

#40 Add index integration tests
  tests/integration/test_index.py
Labels: quality issue fix
