Repository rethinkdb/rethinkdb-python, pull requests merged in 2018-07, with the labels that each got.

#4 Update README.md
  README.md
Labels: documentation

#5 Fix security class codacy issues
  .bandit
  rebirthdb/_export.py
  rebirthdb/_import.py
  rebirthdb/_index_rebuild.py
  rebirthdb/_restore.py
  rebirthdb/gevent_net/net_gevent.py
  rebirthdb/handshake.py
  rebirthdb/logger.py
  rebirthdb/net.py
  rebirthdb/utils_common.py
  requirements.txt
  tests/test_dummy.py
  tests/test_logger.py
Labels: enhancement, quality issue fix

#7 Fixing Connection issue
  rebirthdb/net.py
Labels: bug

#8 Set up integration testing with travis CI
  .travis.yml
  Makefile
  requirements.txt
  tests/helpers.py
  tests/test_logger.py
  tests/test_repl.py
  tox.ini
Labels: enhancement, quality issue fix

#9 Fix codacy issues part 1
  rebirthdb/__init__.py
  rebirthdb/_dump.py
  rebirthdb/_import.py
  rebirthdb/_index_rebuild.py
  rebirthdb/_restore.py
  rebirthdb/ast.py
  rebirthdb/backports/ssl_match_hostname/__init__.py
  rebirthdb/utils_common.py
  rebirthdb/version.py
  setup.py
Labels: quality issue fix

#11 Change query inheritance for pretty printing.
  rebirthdb/ast.py
Labels: bug, enhancement
