Repository rethinkdb/rethinkdb-python, pull requests merged in 2019-04, with the labels that each got.

#105 Add trio test
  requirements.txt
  rethinkdb/trio_net/net_trio.py
  tests/conftest.py
  tests/integration/test_trio.py
Labels: urgent

#114 Cleanup and add python 3.8
  .travis.yml
  requirements.txt
  setup.py
Labels: housekeeping

#106 Fixes changes in 3.7 Multiprocessing for Import/Export and dump/restore
  Makefile
  requirements-dev.txt
  rethinkdb/_export.py
  rethinkdb/_import.py
  rethinkdb/utils_common.py
  setup.py
Labels: bug, urgent

#115 Fix StopIteration exception related issue
  rethinkdb/errors.py
  tests/integration/test_date_and_time.py
  tests/test_date_and_time.py
Labels: bug

#117 Fix setup.py
  setup.py
Labels: bug
